module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-border": "var(--app-border)",
        "app-primary": "var(--app-primary)",
        "app-secondary": "var(--app-secondary)",
        "appdubcodove-gray": "var(--appdubcodove-gray)",
        appdubcomercury: "var(--appdubcomercury)",
        appdubcotundora: "var(--appdubcotundora)",
        appdubcowhite: "var(--appdubcowhite)",
        "backgroundbackground-500": "var(--backgroundbackground-500)",
        backgroundlightcelldefault: "var(--backgroundlightcelldefault)",
        backgroundlightcelldefaulthover:
          "var(--backgroundlightcelldefaulthover)",
        backgroundlightcellselected: "var(--backgroundlightcellselected)",
        backgroundprimary: "var(--backgroundprimary)",
        backgroundtertiary: "var(--backgroundtertiary)",
        "blueblue-500": "var(--blueblue-500)",
        borderlightsecondary: "var(--borderlightsecondary)",
        buttontertiary: "var(--buttontertiary)",
        cellbackgroundcolor: "var(--cellbackgroundcolor)",
        "data-vizgraygray-30": "var(--data-vizgraygray-30)",
        "data-vizgraygray-50": "var(--data-vizgraygray-50)",
        "data-vizlimelime-40": "var(--data-vizlimelime-40)",
        "data-vizpinkpink-10": "var(--data-vizpinkpink-10)",
        "data-vizpinkpink-70": "var(--data-vizpinkpink-70)",
        "data-vizpurplepurple-60": "var(--data-vizpurplepurple-60)",
        error: "var(--error)",
        "error-light": "var(--error-light)",
        fontlightprimary: "var(--fontlightprimary)",
        fontlightsecondary: "var(--fontlightsecondary)",
        gray: "var(--gray)",
        iconprimary: "var(--iconprimary)",
        indigo: "var(--indigo)",
        "paletteblue-20": "var(--paletteblue-20)",
        "primary-1": "var(--primary-1)",
        statestextdisabled: "var(--statestextdisabled)",
        success: "var(--success)",
        "success-light": "var(--success-light)",
        textaccent: "var(--textaccent)",
        "texton-color": "var(--texton-color)",
        textprimary: "var(--textprimary)",
        textsecondary: "var(--textsecondary)",
        "texttext-500": "var(--texttext-500)",
        white: "var(--white)",
        "white-1": "var(--white-1)",
        "whitewhite-500": "var(--whitewhite-500)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-default": "var(--body-default-font-family)",
        "body-defaultstrong": "var(--body-defaultstrong-font-family)",
        "body-small": "var(--body-small-font-family)",
        "body-smallstrong": "var(--body-smallstrong-font-family)",
        "body-tiny": "var(--body-tiny-font-family)",
        "body-tinystrong": "var(--body-tinystrong-font-family)",
        bolder: "var(--bolder-font-family)",
        "caption-small": "var(--caption-small-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h4": "var(--heading-h4-font-family)",
        label: "var(--label-font-family)",
        "label-medium": "var(--label-medium-font-family)",
        "label-small": "var(--label-small-font-family)",
        standard: "var(--standard-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        highlight: "var(--highlight)",
        "innere-shadow-gray-large": "var(--innere-shadow-gray-large)",
        "innere-shadow-white-small": "var(--innere-shadow-white-small)",
        shadow: "var(--shadow)",
        "shadow-centreop4": "var(--shadow-centreop4)",
        "shadow-element": "var(--shadow-element)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
